spec-version: 0.36.0

name: open-browser
version: 0.2.1.1
synopsis: Open a web browser from Haskell
description: |
  Open a web browser from Haskell. Windows, macOS, Linux and BSD are supported.
author: rightfold
homepage: https://github.com/mpilgrem/open-browser
maintainer: public@pilgrem.com
category: Web
tested-with: GHC >= 8.4
github: mpilgrem/open-browser

extra-source-files:
- CHANGELOG.md
- README.md
- stack.yaml
- stack.yaml.lock

flags:
  example:
    description: Build the example application
    default: false
    manual: true

dependencies: base >= 4 && < 5

library:
  source-dirs: lib
  exposed-modules: Web.Browser
  dependencies: process >= 1.4.3.0 && < 2
  when:
  - condition: os(windows)
    then:
      source-dirs: lib/windows
      dependencies: Win32 < 3
    else:
      when:
      - condition: os(darwin)
        then:
          source-dirs:
          - lib/unix-like/common
          - lib/unix-like/open
          dependencies: process >= 1.4.3.0 && < 2
        else:
          when:
          - condition: "os(linux) || os(freebsd) || os(openbsd) || os(netbsd)"
            then:
              source-dirs:
              - lib/unix-like/common
              - lib/unix-like/xdg-open
              dependencies: process >= 1.4.3.0 && < 2
            else:
              source-dirs: lib/unsupported-os

executables:
  open-browser-example:
    when:
    - condition: "!flag(example)"
      buildable: false
    main: Main.hs
    source-dirs: example
    dependencies: open-browser
