spec-version: 0.36.0

name: open-browser
version: 0.2.1.1
synopsis: Open a web browser from Haskell.
description: |
  Open a web browser from Haskell. Currently BSD, Linux, OS X and Windows are
  supported.
author: rightfold
homepage: https://github.com/rightfold/open-browser
maintainer: rightfold@gmail.com
category: Web
tested-with: GHC >= 7.6
github: rightfold/open-browser

extra-source-files:
- CHANGELOG.md
- README.md
- lib/includes/common-include.hs
- stack.yaml
- stack.yaml.lock

flags:
  example:
    description: Build the example application
    default: false
    manual: true

dependencies: base >= 4 && < 5

library:
  exposed-modules: Web.Browser
  dependencies: process >= 1.4.3.0 && < 2
  include-dirs: lib/includes
  default-extensions: CPP
  when:
  - condition: os(windows)
    then:
      source-dirs: lib/windows
      dependencies: Win32
    else:
      when:
      - condition: os(darwin)
        then:
          source-dirs:
          - lib/unix-like/common
          - lib/unix-like/open
        else:
          when:
          - condition: "os(linux) || os(freebsd) || os(openbsd) || os(netbsd)"
            then:
              source-dirs:
              - lib/unix-like/common
              - lib/unix-like/xdg-open
            else:
              source-dirs: lib/unsupported-os

executables:
  open-browser-example:
    when:
    - condition: "!flag(example)"
      buildable: false
    main: Main.hs
    source-dirs: example
    dependencies: open-browser
